### PR TITLE
Use Hubot's Express Server; Respond to Direct Messages to the Bot

### LINKED ISSUE #5: Hubot doesn't react on direct messages when talking directly to him with @myhubot
Hi **all**, I've been playing around with hubot integration of hangouts chat and is not working is said in the documentation, according to it, hubot should answer back on any mention as:

```
MYHUBOT help
myhubot help
@myhubot help
myhubot: help
```
but with google chat integration bot only reacts when it's mentioned with `@` when it's mentioned twice, for example:
```
@myhubot myhubot help
```

after enabling `DEBUG=true` I've seen that in the received body is getting the `raw` message as `text` field but it's processing the field `argumentedText` which strips user's mention.

### possible solution

I've made a small change on the `HangoutsChatTextMessage` object creation to use received `message.text` and then it works as expected, any reason why on the implementation the object is being created with `argumentText`? I haven't seen any difference but mentioned removed from the message.

### raw json body of an example message with mention
```
...
        "text": "@myhubot help",
        "annotations": [
            {
                "type": "USER_MENTION",
                "startIndex": 0,
                "length": 8,
                "userMention": {
                    "user": {
                        "name": "users/USER-ID",
                        "displayName": "myhubot",
                        "avatarUrl": "https://lh4.googleusercontent.com/proxy/URL",
                        "type": "BOT"
                    },
                    "type": "MENTION"
                }
            }
        ],
        "thread": {
            "name": "spaces/THREAD-ID,
            "retentionSettings": {
                "state": "PERMANENT"
            }
        },
        "space": {
            "name": "spaces/SPACE-ID",
            "type": "ROOM",
            "displayName": "test-room"
        },
        "argumentText": " help"
...
```

Thanks!

### PR DESCRIPTION
**Pull request by joeyguerra**
Fixes #5 & #7 

Hubot has its own Express Server. Just use that instead. Also, messages send to the Bot are not being sent to the scripts because the adapter is using `argumentText` which does not include the bot name, i.e. `@hubot`, and the Hubot design requires the bot name to be in the text in order for the scripts to handle it. Specifically, the bot name is in the resulting regular expression pattern that is used to determine if the script has "registered" itself to respond to the message.

I also added tests with actual messages from Google Chat.

### CODE REVIEW

File: src/bot.js [hunk 1]
```diff
@@ -69,29 +63,28 @@ class HangoutsChatBot extends Adapter {
...
     if (thread) {
       data.thread = thread;
     }
-
-    this.robot.logger.info('Sending a message to space: ' + space);
-    if (httpRes) {
-      httpRes.json(data);
-    } else {
-      this.createMessageUsingRestApi_(space, data);
-    }
```
Comment (rtilikay) [inline src/bot.js]: Please continue sending the request using `httpRes.json(data);` for replies if it is present. This way, HTTP bots can still use `res.reply()` without needing a service account.

File: src/bot.js [hunk 2]
```diff
@@ -69,29 +63,28 @@ class HangoutsChatBot extends Adapter {
       thread = undefined,
       text = '',
       cardString = '[]',
-      httpRes = undefined) {
+      httpRes = undefined,
+      done = ()=>{}) {
     if (text == '' && cardString == '[]') {
```
Comment (rtilikay) [inline src/bot.js]: It looks like this callback isn't used except for logging. Could we remove it?

File: src/bot.js [hunk 3]
```diff
@@ -128,17 +123,17 @@ class HangoutsChatBot extends Adapter {
    *     </ul>
    */
   reply(envelope, ...strings) {
+    console.log(envelope, strings)
```
Comment (rtilikay) [inline src/bot.js]: Please use Hubot's logger (`this.robot.logger.debug`).

File: src/bot.js [hunk 4]
```diff
@@ -279,35 +262,28 @@ class HangoutsChatBot extends Adapter {
...
-      // REMOVED_FROM_SPACE event. The user can also force this behavior by
-      // calling message.setHandled() or message.finish().
-      if (!this.isPubSub
-          && (hangoutsChatMessage.handled || hangoutsChatMessage.done)
-          && !res.headersSent) {
-        res.sendStatus(200);
-      }
+    this.robot.receive(hangoutsChatMessage, ()=>{
+      hangoutsChatMessage.finish();
+      hangoutsChatMessage.setHandled();
```
Comment (rtilikay) [inline src/bot.js]: It looks like you'd like to change the logic to always respond to the request, which I agree is a good idea. In this case, we don't need to mark the message as finished / handled.
Please remove references to finish/setHandled. You can leave the `setHandled` function definition to not break any existing users.

File: examples/scripts/cards.js [hunk 5]
```diff
@@ -1,3 +1,19 @@
...
+// Dependencies:
+//
+// Configuration:
+//
+// Commands:
+//   hubot help - will display some help
+//   hubot card - Replies in the same thread as the received message
+//
+// Notes:
+//
```
Comment (rtilikay) [inline examples/scripts/cards.js]: Thank you for adding the documentation! Feel free to remove the help command since it looks like calling `hubot help` will display this command list by default.

File: examples/messages-from-gchat/add-to-room.json [hunk 6]
```diff
@@ -0,0 +1,16 @@
+{
```
Comment (rtilikay) [inline examples/messages-from-gchat/add-to-room.json]: Please rename this directory to `/hangouts-chat-messages/` for consistency. GChat is colloquial for Google Talk.

File: package.json [hunk 7]
```diff
@@ -4,7 +4,9 @@
   "description": "Hangouts Chat Adapter for Hubot",
```
Comment (rtilikay) [inline package.json]: Please bump the version to 2.0.1.

File: src/bot.js (hunk 1 above)
Comment (joeyguerra) [reply src/bot.js]: If the intent is that `resp.reply()` from a script results in replying back to the initial request, I'd like to design that a little bit differently. Let me take a stab at that.

File: src/bot.js (hunk 2 above)
Comment (joeyguerra) [reply src/bot.js]: The callback is used to execute `res.status(200).end()` dependably. It's in ```        this.onEventReceived(req.body, res, ()=>{
          res.status(200).end();
        });
```. If the only scenario where `res.end()` has to be called is if `resp.reply()` is used, then their should be another way to design this too.

File: src/bot.js (hunk 3 above)
Comment (joeyguerra) [reply src/bot.js]: I'll delete that line. I was just debugging.

File: src/bot.js (hunk 4 above)
Comment (joeyguerra) [reply src/bot.js]: Yes, the intent is to ensure they get called at the right time.

File: examples/scripts/cards.js (hunk 5 above)
Comment (joeyguerra) [reply examples/scripts/cards.js]: Will do.

File: examples/messages-from-gchat/add-to-room.json (hunk 6 above)
Comment (joeyguerra) [reply examples/messages-from-gchat/add-to-room.json]: Will do.

File: src/bot.js (hunk 1 above)
Comment (joeyguerra) [reply src/bot.js]: Thinking out loud some more, the response from the script is executed asynchronously so is it really worth having code that writes to the original req/res stream if it's going to be executed asynchronously anyway?

Comment (joeyguerra) [reply src/bot.js]: Can you please elaborate on what a service account is in this context and why one is needed to use `res.reply()`?

Comment (joeyguerra) [reply src/bot.js]: So here's the problem I'm running into. Getting `ERROR Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client` when calling `httpRes.json(data)`. I think it's because `reply` is being executed asynchronously via `process.nextTick()`.

Comment (joeyguerra) [reply src/bot.js]: Another issue with a design that writes to the response, if multiple scripts `reply` to the same message, the design would have to build an array of responses before actually sending the response.

Comment (joeyguerra) [reply src/bot.js]: I think the scenario where multiple scripts respond to the same message requires a design where all of the responses sent independent of each other, not on the same req/resp stream.

Comment (rtilikay) [reply src/bot.js]: > Can you please elaborate on what a service account is in this context and why one is needed to use res.reply()?

A service account is required to use the Hangouts Chat API. Such an account is not needed for the req/res stream, so currently HTTP bots can forego setting up a service account and still be able to use `res.reply()`. 

> if multiple scripts reply to the same message, the design would have to build an array of responses before actually sending the response.

What about using the Chat API for replies beyond the first? The code would look like:

```
if (httpRes && !httpRes.headersSent)
  httpRes.json(data);
else
  this.createMessageUsingRestApi(data);
```

File: src/bot.js (hunk 2 above)
Comment (rtilikay) [reply src/bot.js]: Isn't that the callback in `onEventReceived`? This callback is created in `send`/`reply` and is either empty or logging.

File: src/bot.js (hunk 4 above)
Comment (rtilikay) [reply src/bot.js]: SG, please remove `finish`/`setHandled` if they're not needed.

File: src/bot.js (hunk 1 above)
Comment (joeyguerra) [reply src/bot.js]: Wouldn't that defeat the intent of not requiring a google service account?

File: src/bot.js (hunk 2 above)
Comment (joeyguerra) [reply src/bot.js]: the callback in the original code that called `this.robot.receive` called res.end. However, in the scenario when multiple scripts handle the same message, this design breaks down.

File: src/bot.js (hunk 1 above)
Comment (joeyguerra) [reply src/bot.js]: Another issue is that in the adapters constructor, it automatically tries to sign into google chat with credentials and if there isn't a valid service account, it'll throw errors.

Comment (joeyguerra) [reply src/bot.js]: Ok. I've pushed a design where multiple scripts can handle the same message and reply to it, resulting in those messages being sent as an Array in the response.

Comment (rtilikay) [reply src/bot.js]: > Wouldn't that defeat the intent of not requiring a google service account?

The majority of bot interactions involve a single response to a given command, this is just patching up an edge case.

> if there isn't a valid service account, it'll throw errors.

This only prevents you from using the service account. We should probably change that message to only be an error for Pub/Sub and a warning otherwise.

> resulting in those messages being sent as an Array in the response.

Unfortunately, Hangouts Chat only supports synchronous responses containing a single message, so an array-based approach won't work. I think sending the first reply over HTTP and remaining ones asynchronously through the API is the best approach here.

Comment (joeyguerra) [reply src/bot.js]: That seems to defeat the purpose then. Necessitating a service account for the asynchronous messages. In that case, just make them all asynchronous. Am I missing something here?

Comment (rtilikay) [reply src/bot.js]: Sure, let's do that then. The main reason for using synchronous responses is for backward compatibility, but this is in a new major version and adding a service account is easy, so it isn't that bad.

Comment (joeyguerra) [reply src/bot.js]: After re reading your responses, I think I understand this better. Please correct me if I'm wrong. The assumption you're making is that people will typically ensure that there will be 1 script handling 1 message. If we make this assumption and create a design that assumes it, I want to at least log a warning if there's multiple scripts that handle a single message just to have a better UX for the developer.

Comment (rtilikay) [reply src/bot.js]: Yes, I'm making that assumption. Logging a warning sounds good to me.

Comment (joeyguerra) [reply src/bot.js]: Ok. I've updated the design for this scenario. The first response is sent to the original request. The subsequent responses are sent via the `send` method.

Comment (joeyguerra) [reply src/bot.js]: welp, hold on. gotta defend against `res=null`

Comment (joeyguerra) [reply src/bot.js]: Ok. I've added a check for `isPubSub`.

Comment (joeyguerra) [reply src/bot.js]: Before this is accepted, how do you feel about having 2 adapters, one for HTTP and another for Pub Sub and `main.js` is responsible for choosing which one to `use`?

Comment (rtilikay) [reply src/bot.js]: > The subsequent responses are sent via the send method.

`send` always posts in a new thread. Since `reply` posts in the same thread when possible, we can't use the `send` method for `reply`. Would you be able to still use the model of send/reply letting `postMessage_` do all the work and perform the `headersSent` check there?

> Before this is accepted, how do you feel about having 2 adapters, one for HTTP and another for Pub Sub and main.js is responsible for choosing which one to use?

Personally, I think that the difference between the two flows is too small to warrant having two separate adapters, but I'm open to the idea of splitting them if you have a nice split in mind.

Comment (joeyguerra) [reply src/bot.js]: I'll make the change to use postMessage_. I'll create a different pull request for separating pub/sub and http.

Comment (joeyguerra) [reply src/bot.js]: I've pushed the change.

File: examples/scripts/cards.js [hunk 8]
```diff
@@ -1,3 +1,18 @@
+// Description:
+//   a bot to test this adapter
+//
+// Dependencies:
+//
+// Configuration:
+//
+// Commands:
+//   hubot card - Replies in the same thread as the received message
```
Comment (rtilikay) [inline examples/scripts/cards.js]: Please change to `hubot card - Replies with a card message.`

File: src/bot.js [hunk 9]
```diff
@@ -21,19 +21,14 @@ const PubSub = require(`@google-cloud/pubsub`);
 const {google} = require('googleapis');
 const {auth} = require('google-auth-library');
 const {HangoutsChatTextMessage, AddedToSpaceTextMessage, AddedToSpaceMessage, RemovedFromSpaceMessage, CardClickedMessage} = require('./message')
-const express = require('express');
-const bodyparser = require('body-parser');
-const app = express()
-    .use(bodyparser.urlencoded({extended: false}))
-    .use(bodyparser.json());
 
+let counter = 0;
```
Comment (rtilikay) [inline src/bot.js]: Remove unused variable.

File: src/bot.js [hunk 10]
```diff
@@ -129,18 +114,25 @@ class HangoutsChatBot extends Adapter {
...
+      this.robot.logger.warning('Design assumes a 1 to 1 relationship and more than 1 response was detected.')
+      this.postMessage_(
         this.getSpaceFromEnvelope_(envelope),
-        envelope.message.thread,
+        thread,
         strings[0],
-        strings[1],
-        envelope.message.httpRes,
-        true);
+        strings[1]);
```
Comment (dgliu-f82) [inline src/bot.js]: use text and cardString instead of strings[0] and strings[1]

File: src/bot.js [hunk 11]
```diff
@@ -129,18 +114,25 @@ class HangoutsChatBot extends Adapter {
...
+    const space = this.getSpaceFromEnvelope_(envelope);
+    const thread = envelope.message.thread;
+    const text = strings[0];
+    const cardString = strings[1];
+    const data = this.mapToHangoutsChatResponse(space, text, cardString, thread);
+    this.robot.logger.debug('Adding message to the response: ' + space);
+    if(!this.isPubSub && !envelope.message.httpRes.headersSent){
+      envelope.message.httpRes.json(data);
+    } else {
+      this.robot.logger.warning('Design assumes a 1 to 1 relationship and more than 1 response was detected.')
```
Comment (dgliu-f82) [inline src/bot.js]: This warning doesn't apply to pubsub case.

File: src/bot.js (hunk 1 above)
Comment (rtilikay) [reply src/bot.js]: Sorry to go back and forth on this, but I spoke with Daniel and I think that always using asynchronous responses (i.e. using the API) is better. That way, we also wouldn't need two adapters. Could you please make that change? 

Also, we might want to do a major version bump to 3.0.0 since it might break existing HTTP bots.

Comment (joeyguerra) [reply src/bot.js]: No worries on the back and forth. We're collaborating :)

Are you saying that I should change the code to not use `http.json(data)`? and instead have `reply` execute `postMessage`?

Totally agree about it being a major version change. I'll update the version.

File: package.json (hunk 7 above)
Comment (joeyguerra) [reply package.json]: Gonna bump it to 3.0.0

File: src/bot.js (hunk 1 above)
Comment (rtilikay) [reply src/bot.js]: Yep, stop using http.json(data) and always use the API instead. Thanks!

Comment (joeyguerra) [reply src/bot.js]: Ok. I'm going to press resolve convo....

File: src/bot.js [hunk 12]
```diff
@@ -224,7 +193,8 @@ class HangoutsChatBot extends Adapter {
 
 
   /** Invoked when Event is received from Hangouts Chat. */
-  onEventReceived(event, res) {
+  onEventReceived(req, res, done = ()=>{}) {
```
Comment (rtilikay) [inline src/bot.js]: This breaks Pub/Sub, which passes the event directly. Please change it back to taking in an event or change startPubsubClient to pass in a req object with the event as the body.

File: package.json [hunk 13]
```diff
@@ -15,7 +17,9 @@
     "request": "^2.87.0"
   },
   "devDependencies": {
-    "hubot": "^3.3.2"
```
Comment (rtilikay) [inline package.json]: Are we going to bump the version number here?

Comment (joeyguerra) [reply package.json]: Which version #? I updated the hubot-google-hahgouts-chat version to 3.0.0.  Are you talking about the hubot version?

Comment (joeyguerra) [reply package.json]: I updated the hubot version to the latest version of hubot.

File: src/bot.js (hunk 12 above)
Comment (joeyguerra) [reply src/bot.js]: I fixed it. Let me know what you think.

**Comment by joeyguerra** [comment]
Just pinging the thread to see if there's anything blocking accepting this pull request.

**Comment by joeyguerra** [comment]
@rtilikay is there anything else blocking accepting this pull request?

**Comment by joeyguerra** [comment]
@rtilikay @dgliu-f82 just pinging the thread.

**Comment by rtilikay** [comment]
Sorry, for the delay, merged. Thank you for this pull request! I will update our documentation and push new version to npm in the next few days.
